# Generated by Django 2.0.7 on 2018-07-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_auto_20180715_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
