# Generated by Django 2.0.7 on 2018-07-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_book_book_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_url',
            new_name='image_url',
        ),
    ]
