# Generated by Django 2.0.7 on 2018-07-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_auto_20180715_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.FileField(default='', max_length=500, upload_to=''),
        ),
    ]
