# Generated by Django 2.0.7 on 2018-07-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_auto_20180716_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_taken',
            field=models.CharField(max_length=300),
        ),
    ]
