# Generated by Django 2.0.7 on 2018-07-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0009_auto_20180716_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_taken',
            new_name='taken_by',
        ),
    ]
