# Generated by Django 2.0.7 on 2018-07-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0010_auto_20180716_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_logo_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
