# Generated by Django 2.0.7 on 2018-07-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0011_book_book_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_logo_url',
        ),
    ]
